PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

SELECT DISTINCT ?query ?comment ?content WHERE {
    ?query a sh:SPARQLExecutable .
    ?query rdfs:comment ?comment .
    ?query sh:select ?content .
}
