name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: 24.x

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Use Node.js ${{ env.DEFAULT_NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run linter
        run: yarn run lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Use Node.js ${{ env.DEFAULT_NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build application
        run: yarn run build
        env:
          APPLICATION_ROOT_PATH: /sparql-interface/
      - name: Upload build artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/

  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
